/-
Copyright (c) 2024 Michael Rothgang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michael Rothgang
-/

import Lean.Elab.ParseImportsFast
import Batteries.Data.String.Basic
import Mathlib.Tactic.Linter.TextBased

/-!
# Text-Based Style Linters

This file defines ArkLib's command-line entrypoint for mathlib's Lean text-based style linters.
Run it with:

```bash
lake env lean --run scripts/lint-style.lean
```

The linters themselves are defined in `Mathlib.Tactic.Linter.TextBased`.
The wrapper intentionally avoids Lake workspace APIs so it can run through `lean --run` without
linking ArkLib's native dependency artifacts, and avoids extra executable-only dependencies so it
can run directly after `lake exe cache get`.
-/

open Lean.Linter Mathlib.Linter.TextBased System.FilePath

/-- Imports generated explicitly by umbrella files and not part of ArkLib's source tree. -/
def explicitImports : Array Lean.Name := #[`Batteries, `Std]

/-- Remove non-ArkLib imports generated by `mk_all`. -/
def eraseExplicitImports (names : Array Lean.Name) : Array Lean.Name :=
  explicitImports.foldl Array.erase names

/--
Parse all imports in a text file at `path` and return just their names.
This is a thin wrapper around `Lean.parseImports'`.
-/
def findSourceImports (path : System.FilePath) : IO (Array Lean.Name) := do
  return (← Lean.parseImports' (← IO.FS.readFile path) path.toString).imports
    |>.map (fun imp ↦ imp.module) |>.erase `Init

/-- Read the text-style nolints file. -/
def readStyleNolints : IO (Array String) := do
  let filename : System.FilePath := ("scripts" / "nolints-style.txt")
  try
    IO.FS.lines filename
  catch _ =>
    IO.eprintln s!"warning: nolints file could not be read; treating as empty: {filename}"
    pure #[]

/-- Options for text-based linters. These linters mostly use their own default-enabled options. -/
def textLinterOptions : LinterOptions := {
  toOptions := {}
  linterSets := {}
}

/-- Modules listed in ArkLib's generated umbrella file. -/
def arkLibModules : IO (Array Lean.Name) := do
  return eraseExplicitImports (← findSourceImports "ArkLib.lean")

/-- Parse module-name arguments using Lean's import parser. -/
def parseModuleArgs (mods : Array String) : IO (Array Lean.Name) := do
  let mut result := #[]
  for mod in mods do
    let modParse := Lean.ParseImports.moduleIdent mod {}
    match modParse.error? with
    | none => result := result.append <| modParse.imports.map Lean.Import.module
    | some err => throw <| IO.userError s!"could not parse module name {mod}: {err}"
  return result

/-- Parsed command-line arguments. -/
structure LintStyleArgs where
  github : Bool := false
  exceptions : Bool := false
  fix : Bool := false
  modules : Array String := #[]

/-- Command-line help text. -/
def usage : String :=
  "Usage: lake env lean --run scripts/lint-style.lean [--github] [--exceptions] [--fix] \
  [MODULE ...]\n\n\
  Run text-based style linters on ArkLib Lean modules.\n\
  If no modules are specified, the linter uses ArkLib.lean.\n\n\
  Options:\n\
    --github  Print errors in a format suitable for GitHub problem matchers.\n\
    --exceptions  Print errors in nolints-style.txt format.\n\
    --fix     Automatically fix style errors, if possible.\n\
    -h, --help  Print this help text."

/-- Parse command-line arguments without depending on `Cli`, which may not be cached in CI. -/
def parseArgs (args : List String) : Except String LintStyleArgs :=
  args.foldlM
    (init := {})
    fun parsed arg =>
      match arg with
      | "--github" => .ok { parsed with github := true }
      | "--exceptions" => .ok { parsed with exceptions := true }
      | "--fix" => .ok { parsed with fix := true }
      | "-h" => .error usage
      | "--help" => .error usage
      | _ =>
          if arg.startsWith "-" then
            .error s!"unknown option: {arg}"
          else
            .ok { parsed with modules := parsed.modules.push arg }

/-- Implementation of the `lint-style` command line program. -/
def lintStyleCli (args : LintStyleArgs) : IO UInt32 := do
  if args.github && args.exceptions then
    throw <| IO.userError "lint-style: use at most one of --github and --exceptions"
  let style : ErrorFormat :=
    if args.github then ErrorFormat.github
    else if args.exceptions then ErrorFormat.exceptionsFile
    else ErrorFormat.humanReadable
  let modules ← if args.modules.isEmpty then arkLibModules else parseModuleArgs args.modules

  if modules.isEmpty then
    throw <| IO.userError
      "lint-style: no modules to lint.\n\nHint: run ./scripts/check-imports.sh first."

  let nolints ← readStyleNolints
  let opts := textLinterOptions
  let numberErrors := (← lintModules opts nolints modules style args.fix)
    + (← modulesNotUpperCamelCase opts modules).toUInt32
    + (← modulesOSForbidden opts modules).toUInt32

  if args.fix then
    return 0
  else
    return min numberErrors 125

/-- The entry point to the style linter command. -/
def main (args : List String) : IO UInt32 := do
  match parseArgs args with
  | .ok parsed => lintStyleCli parsed
  | .error message =>
      IO.eprintln message
      return if message == usage then 0 else 2
